import scrapy

class HousePriceItem(scrapy.Item):
    city = scrapy.Field()
    locality_name = scrapy.Field()
    coordinates = scrapy.Field()
    luxury = scrapy.Field()
    project_property = scrapy.Field()
    power_status = scrapy.Field()
    furnished = scrapy.Field()
    bathrooms = scrapy.Field()
    bedrooms = scrapy.Field()
    property_type = scrapy.Field()
    water_status = scrapy.Field()
    operating_since = scrapy.Field()
    tenants_preferred = scrapy.Field()
    luxury_service = scrapy.Field()
    parking = scrapy.Field()
    sqft_price = scrapy.Field()
    price = scrapy.Field()
